config/routes.rb
Collegememes::Application.routes.draw do
  resources :colleges do
    resources :photos
  end  
  
  match 'admin/index' => 'admin#index'
  match 'admin/getToken' => 'admin#getToken'
  match 'facebook/callback' => 'admin#callback'
  match 'admin/update' => 'admin#update'
  match 'admin/addcollege' => 'admin#addCollege'
    match 'about' => 'colleges#about'
  match ':id' => 'colleges#show'
  root :to => 'colleges#index'

end

app/models/college.rb
require 'ap'
class College
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, :type => String
  field :short, :type => String
  field :url, :type => String
  field :fbid, :type => Integer
  validates_uniqueness_of :fbid
  key :short
  cache
  embeds_many :photos
  
  def self.getPhotos(college)
    puts "Updating #{college.name}"
    @token ||= Koala::Facebook::API.new(Token.first.token)
    feed = @token.get_connections(college.fbid, 'feed', {:limit => 50}).keep_if{|d| d['type'] == 'photo'}
    process(feed, college)
    while (feed.next_page_params) do
      feed = feed.next_page.keep_if{|d| d['type'] == 'photo'}
      process(feed, college)
    end
  end
  
  def self.process (feed, college)
    pictures = @token.batch do |batch_api|
      feed.each do |photopost|
        batch_api.get_object(photopost['object_id'])
      end
    end
    likes = @token.batch do |batch_api|
      pictures.each do |picture|
        picture.class == Hash ? batch_api.get_connections(picture['id'], 'likes', {:limit => 100000}) : batch_api.get_connections('10151252892950397','likes',{:limit => 1})
      end
    end
    records = []
    pictures.zip(likes).each {|d| if d.first.class == Hash;  d.first['likecount'] = d.last.nil? ? 0 : d.last.length; records.push (d.first); end}
    records.each do |photo|
    record = college.photos.find_or_create_by({ :fbid => photo['id']})
    record.update_attributes({
      :fbid => photo['id'],
      :thumburl => photo['images'][1]['source'],
      :fullurl => photo['images'][0]['source'],
      :likes => photo['likecount'],
      :created_at => Time.parse(photo['created_time'])
    })
    end
  end
end

app/models/collegejob.rb
class CollegeJob < Object
    def perform
      College.all.each {|d| College.getPhotos(d)}
    end
end

app/models/photo.rb
class Photo
  include Mongoid::Document
  field :fbid, :type => Integer
  field :thumburl, :type => String
  field :fullurl, :type => String
  field :created_at, :type => String
  key :fbid
  embedded_in :college, :inverse_of => :comments
end

app/models/proposed_college.rb
class ProposedCollege
  include Mongoid::Document
  field :name, :type => String
  field :short, :type => String
  field :url, :type => String
end

app/models/token.rb
class Token
  include Mongoid::Document
  field :token, :type => String
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate, :only => [:fetch, :update, :addCollege, :getToken, :index]

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['httpusername'] && password == ENV['httppassword']
    end
  end
  
  def getToken    
@oauth = Koala::Facebook::OAuth.new(ENV['fbid'], ENV['fbsecret'], facebook_callback_url)
redirect_to @oauth.url_for_oauth_code (
  {
    :permissions => [:offline_access, :read_stream]
  })
  end
  
  def callback
    @oauth = Koala::Facebook::OAuth.new(ENV['fbid'], ENV['fbsecret'], facebook_callback_url)
    token =  @oauth.get_access_token params[:code]
    Token.all.each {|d| d.destroy}
    Token.create ({:token => token})
    render :json => token

  end
  
  def update
    Delayed::Job.enqueue CollegeJob.new
    render :json => College.all.map{|d| d.name}
  end
  
  def index
    @colleges = College.all
    @proposed = ProposedCollege.all
    @college = College.new 
  end
  
  def addCollege
    College.create (params[:college])
     render :text => 'sdsd'
  end
  
  
end

class CollegeJob < Object
    def perform
      College.all.each {|d| College.getPhotos(d)}
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  respond_to :html
  def index
    @colleges = College.all.asc(:name)
  end
  
  def show
    @college = College.where("this.short.toLowerCase() == '#{params[:id]}'").first
  end
  
  def create
    @college = ProposedCollege.create(params[:proposed_college])
    redirect_to :root, :notice => 'Thanks for submitting ' + @college.name
  end
  
  def about
    @college = ProposedCollege.new
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  respond_to :json
  def index
    params[:sort] = params[:sort] ? params[:sort] : 'likes'
    params[:range] = params[:range] ? params[:range].to_i : 1000000000000
    respond_with College.where("this.short.toLowerCase() == '#{params[:college_id]}'.toLowerCase()").first.photos.where(:created_at.gt => params[:range].days.ago).desc(params[:sort]).paginate :page => params[:page], :per_page => 20
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/admin/index.html.erb
<%=  @colleges.map{|d| {:name => d.name, :short => d.short, :url => d.url, :fbid => d.fbid}}.to_json  %>

Photos:
<%= @colleges.map{|d| d.photos.count}.to_json %>
Jobs:
<%= Delayed::Job.all.count %>
Proposed:
<%= @proposed.all.to_json %>
<%= form_for @college, :url => admin_addcollege_path, :html => {:class => "nifty_form"} do |f| %>
  Name: <%= f.text_field :name %>
  Short: <%= f.text_field :short %>
  URL: <%= f.text_field :url %>
  FBID: <%= f.text_field :fbid %>
  <%= f.submit "Create" %>
<% end %>

app/views/colleges/about.html.erb
<div class="row">
  <p>
    Tired of not being able to see the most popular memes of the day or all time. Bookmark this site and check in from time to time.
  </p>
  <p>
    If you don't see your college here, shoot me a mail at <a href="mailto:nam@nambrot.com">nam@nambrot.com</a>, or on <a href="http://www.facebook.com/namchuhoai">Facebook</a> via FBMessage.
  </p>
  <p>If you have the data, you can also add it here:</p>
  <%= form_for @college, :url => colleges_path, :html => {:class => "nice"} do |f| %>
      <label>Name:</label>
     <%= f.text_field :name, :class => 'nice input-text' %>
           <label>Short Name:</label>
     <%= f.text_field :short, :class => 'nice input-text' %>
          <label>Url:</label>
    <%= f.text_field :url, :class => 'nice input-text' %>
    <%= f.submit "Create" %>
  <% end %>
  <p>
    If you like this, maybe you wanna check out <a href="http://fbphotobrowser.herokuapp.com">my facebook photo viewer</a>. You can also view the source of this website is on <a href="https://github.com/nambrot/Campusmemes">Github</a>. My personal website is at <a href="http://www.nambrot.com">www.nambrot.com</a>.
  </p>
</div>

app/views/colleges/index.html.erb
  <% @colleges.each do |college| %>
  <div class="college" style="text-align: center;">
    <div class="row">
      <h5>
        <%= college.name %>
      </h5>
      <div class="row">
        <div class="six columns leftbutton">
            <%= link_to 'Go to the Memes', college_path(college.short),  :class => 'button' %>
        </div>
        <div class="six columns rightbutton">
          <a href="<%= college.url  %>" class="button">Go to Facebook Group</a>
        </div>
      </div>
    </div>
    
  </div>
  
  <% end  %>
  
  <p>Can't find your college? Add it here: <a href="/about">About</a></p>

app/views/colleges/show.html.erb
<div class="row">
<p>
  You are currently viewing the memes for <%= @college.name %>
</p>

<ul id="rangepicker">
  <li>Date Range:</li>
  <li><button data-range="1">Day</button></li>
  <li><button data-range="7">Week</button></li>
  <li><button data-range="30">Month</button></li>
  <li><button data-range="100000000000" class="selected">All</button></li>
</ul>
<ul id="sortpicker">
  <li>Sort By:</li>
  <li><button data-sort="likes" class="selected">Like</button></li>
  <li><button data-sort="created_at">Time</button></li>
</ul>
</div>
<div class="row">
<div class="photos">

</div>
</div>
<script type="text/javascript"><!--
google_ad_client = "ca-pub-2746450756036859";
/* Campus Memes */
google_ad_slot = "6008257790";
google_ad_width = 728;
google_ad_height = 90;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<script type="text/javascript">
  var photos = new Photos([],{college: '<%= @college.short %>'});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Collegememes</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-29109732-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
  <meta name="title" content="Campusmemes" />
  <meta name="description" content="Find the best memes sorted by likes" />
</head>
<body>
<div class="row">
  <div class="row">
    <header>
      <ul>
        <li><a href="/" class="button">Switch to another College</a></li>
        <li><a href="/about" class="button">About</a></li>
      </ul>
      <a href="/"><h1>College Memes</h1></a>
      
    </header>
  </div>
  <% flash.each do |key, value| %>

      <%= content_tag(:div, value, :class => "alert-box success") %>

    <% end %>

  <div class="row">
    <%= yield %>
  </div>

</div>

</body>
</html>